#!/bin/bash

run(){
  clear
  echo "Would you like to scan for new messages? or send a new message? (1), (2)"

  #Receive the user response
  read -p ">> " scanorsend

  #If user elects to scan
  if [ $scanorsend == '1' ]
  then 

    #Get the messages
    bash receive

    #ASK to delete
    echo "Would you like to delete their message? (Y/N)"
    read -p ">> " clean 
    if [ $clean == 'Y' -o $clean == 'y' ]
    then bash cleanup
      echo "Message deleted!"
    elif [ $clean == 'N' -o $clean == 'n' ]
    then echo "Message(s) saved!"
    else
      echo "No answer provided. Message(s) saved."
    fi
    echo \[Press enter to continue\]
    read
  elif [ $scanorsend == '2' ]
  then echo "What would you like to say?"
    read -p ">> " newwrite
    date >> .talk.txt
    echo "$USER: $newwrite" >> .talk.txt
    echo -e "\033[0;31mNEW MESSAGE" > .messagealert
    echo Message sent! \[Press enter\]
    read
  else
    echo "Invalid Response"
    sleep 1
  fi
  run
}

cntrl-c(){
  echo "Goodbye!"
  cd ~
  exit
}

trap cntrl-c SIGINT
run  
