#!/bin/bash

#When you delete the .rmold.sh comment, the program will delete the whole mult directory.

#cp -rf .mult ~
.multlocale
echo "Ready to be setup. Go home and cd into .mult and read the README.md"
