#!/bin/bash

#Save the location of the installer to be deleted
oldmultlocation=$PWD

#Receive the second user on the system
echo "Who is the second user in your IM system?"
read -p ">> " user2

if [ -d /Users/$user2 ]
then echo "User $user2 exists PASS"
else
  echo "That user does not exist"
  echo "Installation aborted"
  exit
fi

#Set up the alert file
echo "alert(){
  cd ~$user2/.mult/
  cat .messagealert
}
alert" > ~/.alert

#cleanup file setup
echo "cd ~$user2/.mult/
rm .talk.txt
touch .talk.txt
chmod 666 .talk.txt" > ./.mult/cleanup

#receive file setup
echo "cd ~$user2/.mult/
cat .talk.txt" > ./.mult/receive

#.bashrc setup
if [ -f ~/.bashrc ]
then
  echo "rmnotify(){
    bash ~/.alert
    cd ~$user2/.mult/
    echo \"\" > .messagealert
    cd ~
  }
  rmnotify
mult(){
    cd ~/.mult/
    bash main
    cd ~
}" >> ~/.bashrc
else
  echo "rmnotify(){
    bash ~/.alert
    cd ~$user2/.mult/
    echo \"\" > .messagealert
    cd ~
  }
  rmnotify
mult(){
    cd ~/.mult/
    bash main
    cd ~
}" > ~/.bashrc
fi

#Copy needed files to the user's home directory and set read/write access to all
cp -r .mult ~
chmod 777 ~/.mult

#cd to that home directory
cd ~/.mult

#Remove the old mult directory
rm -rf $oldmultlocation
