#!/bin/bash

# Save the location of the installer to be deleted
oldmultlocation=$PWD

# Receive the second user on the system
echo "Who is the second user in your IM system?"
read -p ">> " user2

if [ -d ~/../$user2 ]
then 
  echo "User $user2 exists"
else
  echo "That user does not exist"
  echo "Installation aborted"
  exit
fi

# cleanup setup
echo """
cleanup(){
  cd ~$user2/.mult/
  rm -f .talk.txt
  touch .talk.txt
  chmod 666 .talk.txt
}""" >> ./.mult/main

# receive setup
echo """
receive(){
  cd ~$user2/.mult/
  cat .talk.txt
}""" >> ./.mult/main

echo "run" >> ./.mult/main

# .bashrc setup
if [ -f ~/.bashrc ]
then echo """
rmnotify(){
  if [ -f ~$user2/.mult/.messagealert ]
  then 
    cat $user2/.mult/.messagealert
    rm -f $user2/.mult/.messagealert
  fi
  cd ~
}
rmnotify
mult(){
  cd ~/.mult/
  bash main
  cd ~
}""" >> ~/.bashrc
else
  echo """
rmnotify(){
  if [ -f ~$user2/.mult/.messagealert ]
  then 
    cat $user2/.mult/.messagealert
    rm -f $user2/.mult/.messagealert
  fi
  cd ~
}
rmnotify
mult(){
  cd ~/.mult/
  bash main
  cd ~
}""" > ~/.bashrc
fi

# Copy needed files to the user's home directory and set read/write access to all
cp -r .mult ~
chmod 777 ~/.mult

# Go home to finish the installation
cd ~

# Remove the old mult directory
rm -rf $oldmultlocation

# Source their bashrc for them
. .bashrc
